//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjNovelReader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNovelTextC
    {
        public int NovelTextId { get; set; }
        public Nullable<int> NovelId { get; set; }
        public Nullable<int> ChapterNum { get; set; }
        public string Text { get; set; }
    
        public virtual tNovel tNovel { get; set; }
    }
}
